[project]
name = "ligoskopos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Hermes-erm", email = "None@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "google-genai>=2.21.0",
    "httpx>=0.28.1",
    "json-repair>=0.63.4",
    "openai>=3.7.0",
    "prompt-toolkit>=3.0.53",
    "pydantic>=2.13.5",
    "rich>=15.0.0",
]

[project.scripts]
ligoskopos = "ligoskopos:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false

[dependency-groups]
dev = [
    "watchfiles>=1.2.0",
]
